### ISSUE TITLE
Which training data were used to train this model?

### ISSUE THREAD

**Issue by b-gran** [Senzing/libpostal-data#12]
Hello,

The [libpostal documentation](https://github.com/openvenues/libpostal#installation-with-an-alternative-data-model) states the following about the Senzing model:
> The data for this model is gotten from [OpenAddress](https://openaddresses.io/), [OpenStreetMap](https://www.openstreetmap.org/) and data generated by Senzing based on customer feedback (a few hundred records), a total of about 1.2 billion records of data from over 230 countries, in 100+ languages. The data from OpenStreetMap and OpenAddress is good but not perfect so the data set was modified by filtering out badly formed addresses, correcting misclassified address tokens and removing tokens that didn't belong in the addresses, whenever these conditions were encountered.

**Is the complete training data that you used to train the Senzing libpostal model available somewhere?** It sounds like it's a filtered and cleaned version of the original libpostal data with some additional data added. Even a filtered and cleaned version of the original dataset (without your confidential customer data) would be beneficial to the community.

Thanks

**Comment by oskar700** [comment]
Thanks for the request. We plan to post future versions or the training data on archive.org.  We are working on the next version and it will hopefully be posted before the end of the year.  We won't post the last version for various reasons.

**Comment by oskar700** [comment]
We provided the data set in the latest version:
https://github.com/Senzing/libpostal-data?tab=readme-ov-file#training-data
