### ISSUE TITLE
Provide test data set

### ISSUE THREAD

**Issue by stauntonjr** [Senzing/libpostal-data#9]
To compare senzing's model and libpostal's original model side-by-side, we made two Dockerfiles (in one of which we installed the senzing model and in the other we installed the default model). We then mounted ~100,000 addresses and a test script to parse addresses in each container and found the output results produced by each were identical. 

I expect this merely reflects a configuration error in how we built libpostal and/or installed pypostal. However, there seems to be no simple way to validate the installation explicitly and confirm which data directory and model is being used, as far as I can tell. 

One way to confirm or deny that the senzing model is indeed being used as expected in the container would be to use the reference data cited in your README. 

Please kindly include in the repository the data set of 12950 addresses that was used to test and verify the model. If this test set was available, the expected difference in results between the senzing model and the original libpostal model could be positively confirmed or denied and aid in our ability to troubleshoot the model configuration on our end.

**Comment by oskar700** [comment]
Thank you for the data and thanks for the suggestion. We plan to make the test data set (or subset of it) available in the future. We included customer data in it and we will need to groom the set before it can be made available.

Here are a few addresses you can use to verify the installed model:
wankengasse 10, 2560 berndorf sankt veit an der triesting at
banco de las garzas 885, las grutas 8521
30000 26th avenue south, federal way 98003
19190 old state highway 120, groveland 95321
RR 2 Box 152

They will parse differently between the models.

Here is the Senzing data model parsing:
`> wankengasse 10, 2560 berndorf sankt veit an der triesting at

Result:

{
  "road": "wankengasse",
  "house_number": "10",
  "postcode": "2560",
  "suburb": "berndorf",
  "city": "sankt veit an der triesting",
  "country": "at"
}

> banco de las garzas 885, las grutas 8521

Result:

{
  "road": "banco de las garzas",
  "house_number": "885",
  "city": "las grutas",
  "postcode": "8521"
}

> 30000 26th avenue south, federal way 98003

Result:

{
  "house_number": "30000",
  "road": "26th avenue south",
  "city": "federal way",
  "postcode": "98003"
}

> 19190 old state highway 120, groveland 95321

Result:

{
  "house_number": "19190",
  "road": "old state highway 120",
  "city": "groveland",
  "postcode": "95321"
}

> RR 2 Box 152

Result:

{
  "road": "rr 2",
  "house_number": "box 152"
}`

And here you have the libpostal-out-of-the-box model parsing:
`> wankengasse 10, 2560 berndorf sankt veit an der triesting at

Result:

{
  "road": "wankengasse",
  "house_number": "10",
  "postcode": "2560",
  "city": "berndorf sankt veit an der triesting",
  "country": "at"
}

> banco de las garzas 885, las grutas 8521

Result:

{
  "house": "banco de las",
  "road": "garzas",
  "house_number": "885",
  "road": "las grutas",
  "postcode": "8521"
}

> 30000 26th avenue south, federal way 98003

Result:

{
  "house_number": "30000",
  "road": "26th avenue south federal way",
  "postcode": "98003"
}

> 19190 old state highway 120, groveland 95321

Result:

{
  "house_number": "19190",
  "road": "old state highway 120 groveland",
  "postcode": "95321"
}

> RR 2 Box 152

Result:

{
  "road": "rr 2 box",
  "house_number": "152"
}`

I hope this helps.

**Comment by oskar700** [comment]
We provided the test data in the latest release:
https://github.com/Senzing/libpostal-data/blob/main/files/tests/v1.1.0/test_data.csv
